apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: blog.mikeventarola-net
  namespace: default
spec:
  secretName: blog.mikeventarola-net-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: blog.mikeventarola.net
  dnsNames:
  - blog.mikeventarola.net
