---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.40
    path: /opt/nfs/wordpress
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: wordpress-nfs-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.40
    path: /opt/nfs/mariadb
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: mariadb-nfs-pvc
